#!/usr/bin/env bash
# Copyright 2019-2021 releng-tool
set -e

# map of versions to documentation references
declare -A versions
versions=(
    ['development']='master'
    ['0.9']='v0.9'
    ['0.8']='v0.8'
    ['0.7']='v0.7'
    ['0.6']='releng-tool-0.6.x'
    ['0.5']='v0.5'
    ['0.4']='v0.4'
    ['0.3']='releng-tool-0.3.x'
    ['0.2']='releng-tool-0.2.x'
    ['0.1']='releng-tool-0.1.x'
)
