#!/usr/bin/env bash
# Copyright 2019 releng-tool
set -e

# map of versions to documentation references
declare -A versions
versions=(
    ['master']='master'
    ['0.1']='releng-tool-0.1.x'
)

# fixed order of versions
ordered_versions=(
'master',\
'0.1'
)
