#!/usr/bin/env bash
# Copyright 2019-2021 releng-tool
set -e

################################################################################

help=0
target=
target_dir=
while [ "$#" -gt 0 ]; do
    case $1 in
        --help)
        help=1
        break 2
        ;;
        --version)
        target="$2"
        shift
        ;;
        --version-dir)
        target_dir="$2"
        shift
        ;;
    esac
    shift
done

if [ $help -eq 1 ]; then
    cat << HELP_EOM
update <options>

 -h, --help                show this help
 --version <version>       build only a specific version
 --version-dir <dir>       prepared directory to use for the version build
HELP_EOM
    exit 0
fi

if [ -n "$target_dir" ]; then
    if [ -z "$target" ]; then
        echo "error) provided a version directory without a version"
        exit 1
    fi
fi

################################################################################

base="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source $base/common
source $base/settings

for version in "${!versions[@]}"; do
    # skip version if not matching to the target (if set)
    if [ -n "$target" ]; then
        if [ "$version" != "$target" ]; then
            continue
        fi
    fi

    echo -e "\e[7mupdating $version (pot)...\e[0m"
    if [ -n "$target_dir" ]; then
        export RELENG_TARGET_DIR=$target_dir
    else
        # checkout specific documentation version
        reference=${versions[$version]}
        git \
            --git-dir="$base/$doc_container/.git" \
            --work-tree="$base/$doc_container" \
            checkout $reference --force
        export RELENG_TARGET_DIR=$base/$doc_container
    fi

    # generate translation files
    export RELENG_LOCALE_DIR=$base/locale-$version/
    python -m sphinx -b gettext . $base/locale-$version

    for ref in $(ls -d $base/locale-$version/*/LC_MESSAGES); do
        lang_dir=${ref%/*}
        lang_dir=${lang_dir%%/}
        lang=${lang_dir##*/}

        # update language files
        echo -e "\e[7mupdating $version ($lang)...\e[0m"
        python -m sphinx_intl update -p $base/locale-$version -l $lang
    done
done
